annotation('textbox', [0.1 0.45 0.5 0.45], ...
    'String', {'$S_{V_g}^T = \frac{sL + R}{sL + R + D V_g}$', ...
               '$S_R^T = \frac{R}{sL + R + D V_g}$', ...
               '$S_L^T = \frac{sL}{sL + R + D V_g}$'}, ...
    'Interpreter', 'latex', ...
    'FontSize', 14, ...
    'EdgeColor', 'none')
annotation('textbox', [0.1 0.35 0.5 0.35], ...
    'String', {'$E_{V_g} = \frac{R}{K_i V_g}$', ...
               '$E_R = \frac{R}{K_i V_g}$', ...
               '$E_L = 0$'}, ...
    'Interpreter', 'latex', ...
    'FontSize', 14, ...
    'EdgeColor', 'none')

annotation('textbox', [0.3 0.45 0.7 0.45], ...
    'String', {'$R = 0.08233 \Omega$', ...
               '$V_g = 24 V$', ...
               '$L = 28.306 {\mu}F$', ...
               '$K_p = 2.13422$', ...
               '$K_i = 6207.54$'}, ...
    'Interpreter', 'latex', ...
    'FontSize', 14, ...
    'EdgeColor', 'none')

annotation('textbox', [0.3 0.35 0.7 0.35], ...
    'String', {'$E_{V_g} = 0.55262 * 10^{-6}$', ...
               '$E_R = 0.55262 * 10^{-6}$', ...
               '$E_L = 0$'}, ...
    'Interpreter', 'latex', ...
    'FontSize', 14, ...
    'EdgeColor', 'none')